version: '3'
volumes:
  postgres-data:
  
services:
  backend-golang:
    build: 
      context: ./.devcontainer/be-db-container/
      dockerfile: Dockerfile
    env_file:
        - ./.devcontainer/be-db-container/.env
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    network_mode: service:db-postgres
    
  db-postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.devcontainer/be-db-container/.env
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  frontend-nextjs:
    build: 
      context: ./.devcontainer/fe-container/
      dockerfile: Dockerfile
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity